name: "CI"

on:
    pull_request:
    push:
        branches:
            - 'master'
env:
    fail-fast: true
    TZ: "Europe/Paris"

jobs:
    phpunit:
        name: "PHPUnit (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.2'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
            -
                name: "Run PHPUnit"
                run: "php -dzend.assertions=1 vendor/bin/phpunit"
    phpunit-lowest:
        name: "PHPUnit Lowest Deps (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.2'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
                    dependency-versions: "lowest"
            -
                name: "Run PHPUnit"
                run: "php -dzend.assertions=1 vendor/bin/phpunit"
    psalm:
        name: "Psalm (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.2'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
            -
                name: "Run Psalm"
                run: "vendor/bin/psalm"
    php-cs-fixer:
        name: "PHP-CS-Fixer (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.2'
        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
            -
                name: "Run PHP-CS_Fixer"
                run: "vendor/bin/php-cs-fixer fix --dry-run"

    docs:
        name: "PHP-CS-Fixer (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '8.2'
        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"
            -
                name: "Run docs"
                run: "GHERKINLINT_DEV=1 bin/gherkinlint ruledocs docs/rules.md"
